title: "My Course"
description: "A comprehensive course on data science."
baseurl: "/my-course-webpage" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-cayman # the theme you selected
